# Generated by Django 4.1.5 on 2023-01-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amount', '0006_mygroup_myuser_mymembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='mymembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyGroup',
        ),
        migrations.DeleteModel(
            name='MyMembership',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
