# Generated by Django 4.1.5 on 2023-01-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amount', '0007_remove_mymembership_group_remove_mymembership_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='Name',
        ),
        migrations.AddField(
            model_name='amount_list',
            name='Paid_To',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
