# Generated by Django 4.1.5 on 2023-01-09 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amount', '0008_remove_amount_name_amount_list_paid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount_list',
            name='user_name_list',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
