# Generated by Django 4.1.5 on 2023-01-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amount', '0009_amount_list_user_name_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount_list',
            name='user_name_list',
        ),
    ]
